# Generated by Django 3.0.6 on 2020-05-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_category',
        ),
        migrations.AddField(
            model_name='post',
            name='image_category',
            field=models.ManyToManyField(to='gallery.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_name',
            field=models.CharField(default=models.ImageField(default='none', upload_to='articles/'), max_length=255),
        ),
    ]
