# Generated by Django 3.0.6 on 2020-05-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='none', upload_to='static/images/articles/'),
        ),
    ]
